# Generated by Django 5.0.6 on 2024-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_profetion_alter_mydata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='mydata',
            name='education',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
