# Generated by Django 5.0.6 on 2024-10-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_adress_mydata_address_mydata_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '1. Link',
            },
        ),
        migrations.AlterModelOptions(
            name='mydata',
            options={'verbose_name_plural': '2. Mydata'},
        ),
    ]
