# Generated by Django 5.0.6 on 2024-10-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_links_alter_mydata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
                ('company', models.CharField(default='-----', max_length=100)),
                ('job_role', models.CharField(default='-----', max_length=100)),
                ('address', models.CharField(default='-----', max_length=100)),
            ],
            options={
                'verbose_name_plural': '3. Experience',
            },
        ),
    ]
