# Generated by Django 5.0.6 on 2024-10-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mydata'),
        ),
    ]
