# Generated by Django 5.0.6 on 2024-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_experience_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_percentage', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '4. Skill',
            },
        ),
    ]
