# Generated by Django 5.0.6 on 2024-10-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_code_editor_hobbies_language_soft_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='domain',
            field=models.CharField(default='-----', max_length=50, null=True),
        ),
    ]
