# Generated by Django 5.0.6 on 2024-10-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_about_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='About',
            new_name='about',
        ),
    ]
