# Generated by Django 5.0.6 on 2024-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_about_about_resume_about_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Profetion',
            field=models.CharField(default='-----', max_length=100),
        ),
    ]
