# Generated by Django 5.0.6 on 2024-10-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_experience_profetion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Profetion',
            new_name='Position',
        ),
    ]
