# Generated by Django 5.0.6 on 2024-10-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_profetion_experience_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='education',
            new_name='high_education',
        ),
    ]
