# Generated by Django 5.0.6 on 2024-10-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='std',
            field=models.CharField(choices=[('Secondary School', 'Secondary School'), ('Higher Secondary School', 'Higher Secondary School'), ('Bachelor of Science', 'Bachelor of Science')], max_length=50),
        ),
    ]
