# Generated by Django 5.0.6 on 2024-10-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_education_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
