# Generated by Django 5.0.6 on 2024-10-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_education_degree_alter_education_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': '10. Education'},
        ),
        migrations.AlterField(
            model_name='education',
            name='branch',
            field=models.CharField(default='-----', max_length=30),
        ),
    ]
