# Generated by Django 5.0.6 on 2024-10-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_education_options_alter_education_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='Icon',
            field=models.CharField(help_text='boostrap class', max_length=100, null=True),
        ),
    ]
