# Generated by Django 5.0.6 on 2024-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_links_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='Icon',
        ),
        migrations.AddField(
            model_name='links',
            name='icon',
            field=models.CharField(help_text='Enter Icon boostrap class ex.icon-youtube', max_length=100, null=True),
        ),
    ]
