# Generated by Django 5.0.6 on 2024-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_links_icon_links_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='photo',
            new_name='background_img',
        ),
        migrations.AddField(
            model_name='mydata',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='media/myphoto'),
        ),
    ]
